/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ImageRouteImport } from './routes/image'
import { Route as BillsRouteImport } from './routes/bills'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/bills': typeof BillsRoute
  '/image': typeof ImageRoute
  '/notes': typeof NotesRoute
}
export interface FileRoutesByTo {
  '/bills': typeof BillsRoute
  '/image': typeof ImageRoute
  '/notes': typeof NotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/bills': typeof BillsRoute
  '/image': typeof ImageRoute
  '/notes': typeof NotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bills' | '/image' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/bills' | '/image' | '/notes'
  id: '__root__' | '/bills' | '/image' | '/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BillsRoute: typeof BillsRoute
  ImageRoute: typeof ImageRoute
  NotesRoute: typeof NotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BillsRoute: BillsRoute,
  ImageRoute: ImageRoute,
  NotesRoute: NotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
